### ISSUE TITLE
java-zirk-proxy's starter.jar includes logback.xml

### ISSUE THREAD

**Issue by maass-bezirk** [Bezirk-Bosch/Middleware#158]
The settings in this XML file override what a user puts in their own logback.xml. This means if I have a desktop Zirk using logback and I want to use the DEBUG log level I am screwed because starter.jar overrides it and sets the root log level to ERROR.

As a work around, I deleted logback.xml in the starter.jar in my gradle cache. Of course, this is not acceptable to have to do.

Libraries and frameworks are generally not supposed to include log configuration files for this very reason.

**Comment by rishabhgulati** [comment]
#165
