### ISSUE TITLE
Bezirk (3.1.0 android) initialize crashing in Google Pixel

### ISSUE THREAD

**Issue by ascoril** [Bezirk-Bosch/Middleware#170]
Already the following set of code exist:

BezirkMiddleware.initialize(context);
//BezirkMiddleware.initialize(context);
bezirk = BezirkMiddleware.registerZirk(beyond_zirk);

Still crashing:

 Caused by: java.lang.IllegalStateException: Bezirk Service is not running. Start the Bezirk service using BezirkMiddleware.initialize(Context) or BezirkMiddleware.initialize(Context, Config)
                                                                                 at com.bezirk.middleware.android.BezirkMiddleware.registerZirk(BezirkMiddleware.java:139)
                                                                                 at com.bezirk.beyond.BeyondZirk.<init>(BeyondZirk.java:42)
                                                                                 at com.bezirk.beyond.beyondapp.BeyondAppActivity.startBeyondZirk(BeyondAppActivity.java:236)

**Comment by rishabhgulati** [comment]
@ascoril 
We are currently missing documentation on this but here's how to use the Bezirk Middleware in android:
- Initialize the middleware`BezirkMiddleware.initialize()` in the android Application class. This is done to maintain the bezirk instance running while the application is running. The Bezirk Middleware is destroyed when the application is closed by the user. `BezirkMiddleware.stop()` need not be called explicitly to stop the middleware 
- ZIrk's can be registered/unregistered in the activities. 
- You can think of the `BezirkMiddleware` to have the application level scope and the `Bezirk` api handle of each zirk to have activity level scope in android.

Exception is thrown as the initialization of the middleware is not yet completed and the registerZirk is called.

**Comment by ascoril** [comment]
The idea of creating beyond-zirk is to abstract the middleware layer from the app using beyond. With these changes, this idea is no longer vaid. 
Why was the decision taken for 

> You can think of the BezirkMiddleware to have the application level scope and the Bezirk api handle of each zirk to have activity level scope in android

**Comment by rishabhgulati** [comment]
I am not sure how this change affects the beyond-zirk. You would just have global application state initialization in the application class. You could use this directly or wrap it inside beyond.
The primary decision for this was made after seeing the real world use cases of the middleware in applications, which involved having zirk(s) to be used across activities. Middleware initialization in each activity is unnecessary and costly.

**Comment by ascoril** [comment]
beyond-zirk and beyond are two different entities, beyond-zirk uses beyond. It was our idea of giving the ease of using beyond-zirk to personalization app developers to communicate details overs the wire wthout them doing anything, these developers are not suppose to know anything about bezirk middleware. But i also appreciate the changes made to bezirk.
